
package frc.robot.subsystems.choreo;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

// If these imports cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj LeftTrenchShoot1 = new ChoreoTraj(
	    "LeftTrenchShoot1",
	    OptionalInt.empty(),
	    1.74616,
	    new Pose2d(8.719, 2.631, Rotation2d.fromRadians(1.571)),
	    new Pose2d(13.038, 0.639, Rotation2d.fromRadians(-1.297))
	);
	public static final ChoreoTraj LeftTrenchNeutral2 = new ChoreoTraj(
	    "LeftTrenchNeutral2",
	    OptionalInt.empty(),
	    2.51493,
	    new Pose2d(13.038, 0.639, Rotation2d.fromRadians(-1.297)),
	    new Pose2d(8.66, 3.528, Rotation2d.fromRadians(1.571))
	);
	public static final ChoreoTraj RightTrenchShoot2 = new ChoreoTraj(
	    "RightTrenchShoot2",
	    OptionalInt.empty(),
	    2.90027,
	    new Pose2d(8.699, 4.658, Rotation2d.fromRadians(-1.571)),
	    new Pose2d(14.78, 4.639, Rotation2d.fromRadians(0.229))
	);
	public static final ChoreoTraj ClimbRightSide4 = new ChoreoTraj(
	    "ClimbRightSide4",
	    OptionalInt.empty(),
	    1.1086,
	    new Pose2d(15.156, 2.051, Rotation2d.fromRadians(-0.6)),
	    new Pose2d(14.917, 4.522, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj TeleopNeutralLeft = new ChoreoTraj(
	    "TeleopNeutralLeft",
	    OptionalInt.empty(),
	    1.99959,
	    new Pose2d(8.286, 4.036, Rotation2d.fromRadians(0)),
	    new Pose2d(13.096, 7.331, Rotation2d.fromRadians(1.171))
	);
	public static final ChoreoTraj ClimbRightSide3 = new ChoreoTraj(
	    "ClimbRightSide3",
	    OptionalInt.empty(),
	    1.17461,
	    new Pose2d(15.658, 7.378, Rotation2d.fromRadians(0.835)),
	    new Pose2d(14.917, 4.522, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj LeftTrenchShootAlt2 = new ChoreoTraj(
	    "LeftTrenchShootAlt2",
	    OptionalInt.empty(),
	    1.94624,
	    new Pose2d(8.66, 3.528, Rotation2d.fromRadians(1.571)),
	    new Pose2d(13.045, 0.772, Rotation2d.fromRadians(-1.201))
	);
	public static final ChoreoTraj RightTrenchNeutral2 = new ChoreoTraj(
	    "RightTrenchNeutral2",
	    OptionalInt.empty(),
	    2.37036,
	    new Pose2d(13.007, 7.484, Rotation2d.fromRadians(1.267)),
	    new Pose2d(8.699, 4.658, Rotation2d.fromRadians(-1.571))
	);
	public static final ChoreoTraj MidOutpost = new ChoreoTraj(
	    "MidOutpost",
	    OptionalInt.empty(),
	    1.52899,
	    new Pose2d(12.938, 3.996, Rotation2d.fromRadians(0)),
	    new Pose2d(15.658, 7.378, Rotation2d.fromRadians(0.835))
	);
	public static final ChoreoTraj ClimbLeftSide1 = new ChoreoTraj(
	    "ClimbLeftSide1",
	    OptionalInt.empty(),
	    0.68323,
	    new Pose2d(14.858, 3.859, Rotation2d.fromRadians(0)),
	    new Pose2d(14.936, 4.054, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj ClimbRightSide2 = new ChoreoTraj(
	    "ClimbRightSide2",
	    OptionalInt.empty(),
	    1.26164,
	    new Pose2d(13.007, 7.484, Rotation2d.fromRadians(1.267)),
	    new Pose2d(14.917, 4.522, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj ClimbRightSide1 = new ChoreoTraj(
	    "ClimbRightSide1",
	    OptionalInt.empty(),
	    0.62219,
	    new Pose2d(14.78, 4.639, Rotation2d.fromRadians(0.229)),
	    new Pose2d(14.917, 4.522, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj ClimbLeftSide2 = new ChoreoTraj(
	    "ClimbLeftSide2",
	    OptionalInt.empty(),
	    1.33054,
	    new Pose2d(13.038, 0.639, Rotation2d.fromRadians(-1.297)),
	    new Pose2d(14.936, 4.054, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj MidNothing = new ChoreoTraj(
	    "MidNothing",
	    OptionalInt.empty(),
	    1.65736,
	    new Pose2d(12.938, 3.996, Rotation2d.fromRadians(0)),
	    new Pose2d(16.035, 3.989, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj TeleopAllianceLeft = new ChoreoTraj(
	    "TeleopAllianceLeft",
	    OptionalInt.empty(),
	    2.08908,
	    new Pose2d(14.079, 3.996, Rotation2d.fromRadians(3.142)),
	    new Pose2d(10.586, 0.674, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj RightTrenchNeutral1 = new ChoreoTraj(
	    "RightTrenchNeutral1",
	    OptionalInt.empty(),
	    1.69259,
	    new Pose2d(12.169, 7.406, Rotation2d.fromRadians(3.142)),
	    new Pose2d(8.777, 5.204, Rotation2d.fromRadians(-1.571))
	);
	public static final ChoreoTraj ClimbLeftSide3 = new ChoreoTraj(
	    "ClimbLeftSide3",
	    OptionalInt.empty(),
	    0.99094,
	    new Pose2d(15.156, 2.051, Rotation2d.fromRadians(-0.6)),
	    new Pose2d(14.936, 4.054, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj TeleopNeutralRight = new ChoreoTraj(
	    "TeleopNeutralRight",
	    OptionalInt.empty(),
	    2.06087,
	    new Pose2d(8.286, 4.036, Rotation2d.fromRadians(0)),
	    new Pose2d(13.046, 0.707, Rotation2d.fromRadians(-1.298))
	);
	public static final ChoreoTraj TeleopAllianceRight = new ChoreoTraj(
	    "TeleopAllianceRight",
	    OptionalInt.empty(),
	    2.08754,
	    new Pose2d(14.079, 3.996, Rotation2d.fromRadians(3.142)),
	    new Pose2d(10.586, 7.321, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj RightTrenchShootAlt2 = new ChoreoTraj(
	    "RightTrenchShootAlt2",
	    OptionalInt.empty(),
	    1.99064,
	    new Pose2d(8.699, 4.658, Rotation2d.fromRadians(-1.571)),
	    new Pose2d(13.162, 7.214, Rotation2d.fromRadians(1.144))
	);
	public static final ChoreoTraj ClimbLeftSide4 = new ChoreoTraj(
	    "ClimbLeftSide4",
	    OptionalInt.empty(),
	    1.26933,
	    new Pose2d(15.658, 7.378, Rotation2d.fromRadians(0.835)),
	    new Pose2d(14.936, 4.054, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj OutpostCycle = new ChoreoTraj(
	    "OutpostCycle",
	    OptionalInt.empty(),
	    0.9279,
	    new Pose2d(15.658, 7.378, Rotation2d.fromRadians(0.835)),
	    new Pose2d(15.658, 7.378, Rotation2d.fromRadians(0.835))
	);
	public static final ChoreoTraj MidDepot = new ChoreoTraj(
	    "MidDepot",
	    OptionalInt.empty(),
	    1.17886,
	    new Pose2d(12.938, 3.996, Rotation2d.fromRadians(0)),
	    new Pose2d(15.156, 2.051, Rotation2d.fromRadians(-0.6))
	);
	public static final ChoreoTraj LeftTrenchNeutral1 = new ChoreoTraj(
	    "LeftTrenchNeutral1",
	    OptionalInt.empty(),
	    1.65626,
	    new Pose2d(12.11, 0.604, Rotation2d.fromRadians(3.142)),
	    new Pose2d(8.719, 2.631, Rotation2d.fromRadians(1.571))
	);
	public static final ChoreoTraj DepotSwitchOutpost = new ChoreoTraj(
	    "DepotSwitchOutpost",
	    OptionalInt.empty(),
	    1.99024,
	    new Pose2d(15.156, 2.051, Rotation2d.fromRadians(-0.6)),
	    new Pose2d(15.658, 7.378, Rotation2d.fromRadians(0.835))
	);
	public static final ChoreoTraj RightTrenchShoot1 = new ChoreoTraj(
	    "RightTrenchShoot1",
	    OptionalInt.empty(),
	    1.88587,
	    new Pose2d(8.777, 5.204, Rotation2d.fromRadians(-1.571)),
	    new Pose2d(13.007, 7.484, Rotation2d.fromRadians(1.267))
	);
	public static final ChoreoTraj LeftTrenchShoot2 = new ChoreoTraj(
	    "LeftTrenchShoot2",
	    OptionalInt.empty(),
	    3.08771,
	    new Pose2d(8.66, 3.528, Rotation2d.fromRadians(1.571)),
	    new Pose2d(14.858, 3.859, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj DepotCycle = new ChoreoTraj(
	    "DepotCycle",
	    OptionalInt.empty(),
	    1.10202,
	    new Pose2d(15.156, 2.051, Rotation2d.fromRadians(-0.6)),
	    new Pose2d(15.156, 2.051, Rotation2d.fromRadians(-0.6))
	);

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
    	Map.entry("LeftTrenchShoot1", LeftTrenchShoot1),
		Map.entry("LeftTrenchNeutral2", LeftTrenchNeutral2),
		Map.entry("RightTrenchShoot2", RightTrenchShoot2),
		Map.entry("ClimbRightSide4", ClimbRightSide4),
		Map.entry("TeleopNeutralLeft", TeleopNeutralLeft),
		Map.entry("ClimbRightSide3", ClimbRightSide3),
		Map.entry("LeftTrenchShootAlt2", LeftTrenchShootAlt2),
		Map.entry("RightTrenchNeutral2", RightTrenchNeutral2),
		Map.entry("MidOutpost", MidOutpost),
		Map.entry("ClimbLeftSide1", ClimbLeftSide1),
		Map.entry("ClimbRightSide2", ClimbRightSide2),
		Map.entry("ClimbRightSide1", ClimbRightSide1),
		Map.entry("ClimbLeftSide2", ClimbLeftSide2),
		Map.entry("MidNothing", MidNothing),
		Map.entry("TeleopAllianceLeft", TeleopAllianceLeft),
		Map.entry("RightTrenchNeutral1", RightTrenchNeutral1),
		Map.entry("ClimbLeftSide3", ClimbLeftSide3),
		Map.entry("TeleopNeutralRight", TeleopNeutralRight),
		Map.entry("TeleopAllianceRight", TeleopAllianceRight),
		Map.entry("RightTrenchShootAlt2", RightTrenchShootAlt2),
		Map.entry("ClimbLeftSide4", ClimbLeftSide4),
		Map.entry("OutpostCycle", OutpostCycle),
		Map.entry("MidDepot", MidDepot),
		Map.entry("LeftTrenchNeutral1", LeftTrenchNeutral1),
		Map.entry("DepotSwitchOutpost", DepotSwitchOutpost),
		Map.entry("RightTrenchShoot1", RightTrenchShoot1),
		Map.entry("LeftTrenchShoot2", LeftTrenchShoot2),
		Map.entry("DepotCycle", DepotCycle)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
